[buildkite] scheduler works with local and  test mode (#23)
* [buildkite] scheduler works with local

* test mode printed

diff --git a/.buildkite/snapshot-fetch-and-parse.yml b/.buildkite/snapshot-fetch-and-parse.yml
--- a/.buildkite/snapshot-fetch-and-parse.yml
+++ b/.buildkite/snapshot-fetch-and-parse.yml
@@ -2,8 +2,10 @@ agents:
   queue: "snapshots"
 
 env:
-  gs_bucket: gs://marinade-solana-snapshot-mainnet
-  slack_api: https://slack.com/api/chat.postMessage
+  GCLOUD_SNAPSHOTS: "gs://marinade-solana-snapshot-mainnet"
+  LOCAL_SNAPSHOTS: "/mnt/snapshots-storage/snapshots"
+  WORKING_DIR: "/mnt/storage-1/snapshots"
+  slack_api: "https://slack.com/api/chat.postMessage"
   slack_feed: "feed-snapshot"
 
 steps:
@@ -21,10 +23,42 @@ steps:
 
   - wait: ~
 
+  - label: ":black_nib: Env variables setup"
+    key: "setup-env-init"
+    commands:
+    - |
+      epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
+      buildkite-agent meta-data set --redacted-vars='' epoch "$$epoch"
+    - |
+      local_snapshot_dir=${LOCAL_SNAPSHOT_DIR:-$LOCAL_SNAPSHOTS}
+      buildkite-agent meta-data set --redacted-vars='' local_snapshot_dir "$$local_snapshot_dir"
+
+  - label: ":memo: Annotate retry parameters"
+    depends_on: "setup-env-init"
+    allow_dependency_failure: true
+    commands:
+      - epoch=$(buildkite-agent meta-data get epoch)
+      - local_snapshot_dir=$(buildkite-agent meta-data get local_snapshot_dir)
+      - |
+        cat <<- EOF | buildkite-agent annotate --priority 6 --style info --context "general-info"
+        ### Retry environment variables
+        If you need to retry the build, use the following parameters:
+
+        \`\`\`
+        EPOCH=$$epoch
+        LOCAL_SNAPSHOT_DIR=$$local_snapshot_dir
+        TEST_MODE=$$TEST_MODE
+        \`\`\`
+        EOF
+
+  - wait: ~
+
   - label: ":mega: Notification"
     commands:
     - |
       epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
+      local_snapshot_dir=$(buildkite-agent meta-data get local_snapshot_dir)
+      test_mode=$([[ -n "$TEST_MODE" && "$TEST_MODE" != "null" ]] && echo " [Test Mode: $$local_snapshot_dir]" || echo "")
       buildkite-agent meta-data set --redacted-vars="" epoch "$$epoch"
       curl ${slack_api} -X POST -H 'Content-Type: application/json; charset=utf-8' \
         -H "Authorization: Bearer $$SLACK_BEARER_TOKEN" -d '{
@@ -34,7 +68,7 @@ steps:
               "author_name": "Solana Snapshot Parser",
               "author_link": "https://github.com/marinade-finance/solana-snapshot-parser",
               "color": "8000FF",
-              "title": "Parsing Solana Snapshot ('"$$epoch"').",
+              "title": "Parsing Solana Snapshot ('"$$epoch"')'"$$test_mode"'.",
               "title_link": "'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'",
               "footer": "<'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'|View in Buildkite>"
             }
@@ -42,18 +76,16 @@ steps:
       }'
 
   - label: ":file_folder: Prepare snapshot directory"
-    env:
-      target_dir: /mnt/storage-1/snapshots
-      local_storage: /mnt/snapshots-storage/snapshots
     commands:
     - ulimit -a
-    - epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
+    - epoch=$(buildkite-agent meta-data get epoch)
+    - local_snapshot_dir=$(buildkite-agent meta-data get local_snapshot_dir)
     - |
-      mkdir -p $$target_dir
-      snapshot_dir=$(mktemp --directory -p "$$target_dir" "snapshot-$$epoch-$(date +%s)-XXXXXX")
+      mkdir -p $$WORKING_DIR
+      snapshot_dir=$(mktemp --directory -p "$$WORKING_DIR" "snapshot-$$epoch-$(date +%s)-XXXXXX")
 
       # Check if snapshot already exists in local storage
-      local_snapshot=$(find $$local_storage/*/$$epoch/ -name 'snapshot-*.tar.zst' 2>/dev/null | head -1)
+      local_snapshot=$(find $$local_snapshot_dir/*/$$epoch/ -name 'snapshot-*.tar.zst' 2>/dev/null | head -1)
       if [[ -n "$$local_snapshot" ]]; then
         echo "Found local snapshot at: $$local_snapshot"
         ln -s "$$local_snapshot" "$$snapshot_dir/"
@@ -80,7 +112,7 @@ steps:
       else
         snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)
         epoch=$(buildkite-agent meta-data get epoch)
-        ./scripts/fetch-snapshot.bash "$$epoch" "$$snapshot_dir"
+        ./scripts/fetch-snapshot.bash "$$epoch" "$$snapshot_dir" "$GCLOUD_SNAPSHOTS"
       fi
 
   - label: ":hammer_and_wrench: :rust: Build"
@@ -109,18 +141,20 @@ steps:
   - wait: ~
 
   - label: ":floppy_disk: :arrow_left: :cloud: Fetch past validator data"
+    if: build.env("TEST_MODE") == null
     commands:
     - snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)
     - epoch=$(buildkite-agent meta-data get epoch)
     - previous_epoch=$((epoch - 1))
-    - gcloud storage cp "$gs_bucket/$$previous_epoch/validators.json" "$gs_bucket/$$epoch/past-validators.json" || echo "Previous validator data not available!"
+    - gcloud storage cp "$GCLOUD_SNAPSHOTS/$$previous_epoch/validators.json" "$GCLOUD_SNAPSHOTS/$$epoch/past-validators.json" || echo "Previous validator data not available!"
 
   - label: ":floppy_disk: :arrow_right: :cloud: Upload artifacts"
+    if: build.env("TEST_MODE") == null
     commands:
     - snapshot_dir=$(buildkite-agent meta-data get snapshot_dir)
     - epoch=$(buildkite-agent meta-data get epoch)
-    - gcloud storage cp "$$snapshot_dir/validators.json" "$gs_bucket/$$epoch/"
-    - gcloud storage cp "$$snapshot_dir/stakes.json" "$gs_bucket/$$epoch/"
+    - gcloud storage cp "$$snapshot_dir/validators.json" "$GCLOUD_SNAPSHOTS/$$epoch/"
+    - gcloud storage cp "$$snapshot_dir/stakes.json" "$GCLOUD_SNAPSHOTS/$$epoch/"
 
   - wait: ~
 
